# Generated by Django 5.1.3 on 2025-02-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suzlar',
            name='muqobili',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
