# Generated by Django 5.1.3 on 2025-02-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phd', '0002_suzlar_muqobili'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtoqliSuzlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
                ('muqobili', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Muqobillari')),
            ],
            options={
                'verbose_name': "Atoqli so'zlar",
                'verbose_name_plural': "Atoqli so'zlar",
            },
        ),
        migrations.CreateModel(
            name='BoglovchiSozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
                ('muqobili', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Muqobillari')),
            ],
            options={
                'verbose_name': "Bog'lovchi so'zlar",
                'verbose_name_plural': "Bog'lovchi so'zlar",
            },
        ),
        migrations.CreateModel(
            name='BuyruqSozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
                ('muqobili', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Muqobillari')),
            ],
            options={
                'verbose_name': "Buyruq so'zlar",
                'verbose_name_plural': "Buyruq so'zlar",
            },
        ),
        migrations.CreateModel(
            name='KomakchiSozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
                ('muqobili', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Muqobillari')),
            ],
            options={
                'verbose_name': "Ko'makchi so'zlar",
                'verbose_name_plural': "Ko'makchi so'zlar",
            },
        ),
        migrations.CreateModel(
            name='ModalSozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
                ('muqobili', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Muqobillari')),
            ],
            options={
                'verbose_name': "Modal so'zlar",
                'verbose_name_plural': "Modal so'zlar",
            },
        ),
        migrations.CreateModel(
            name='Raqamlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Raqamlar',
                'verbose_name_plural': 'Raqamlar',
            },
        ),
        migrations.CreateModel(
            name='SonlarNomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
                ('muqobili', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Muqobillari')),
            ],
            options={
                'verbose_name': 'Sonlar nomi',
                'verbose_name_plural': 'Sonlar nomi',
            },
        ),
        migrations.CreateModel(
            name='SoroqSozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
                ('muqobili', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Muqobillari')),
            ],
            options={
                'verbose_name': "So'roq so'zlar",
                'verbose_name_plural': "So'roq so'zlar",
            },
        ),
        migrations.CreateModel(
            name='UndoviSozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
                ('muqobili', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Muqobillari')),
            ],
            options={
                'verbose_name': "Undov so'zlar",
                'verbose_name_plural': "Undov so'zlar",
            },
        ),
        migrations.CreateModel(
            name='YondoshFellar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
                ('muqobili', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Muqobillari')),
            ],
            options={
                'verbose_name': 'Yondosh fellar',
                'verbose_name_plural': 'Yondosh fellar',
            },
        ),
        migrations.AlterField(
            model_name='suzlar',
            name='muqobili',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Muqobillari'),
        ),
        migrations.AlterField(
            model_name='suzlar',
            name='name',
            field=models.CharField(default='', max_length=1000, verbose_name='Nomi'),
        ),
    ]
